### PR TITLE
Edit stats03

### LINKED ISSUE #128: [PE-D] Inaccurate stats when there are multiple employees have the shortest tenure
It is really useful that the program shows the stats about the shortest tenure and list down the relevant employees.
It works well when there is a single employee who has the shortest tenure.
However, the program failed to display multiple employees who have the shortest tenure.
Suggestion: display all matched employees' names or display No.of people who matched.

For testing purpose:
#5 ABC2 Join date:2020-02-01
#6 David Li Join date:2020-02-01
#7 Irfan Ibrahim Join date:2020-02-01
These three people share the same join date, and the join date is the shortest tenure.
By right, the program shall list down both ABC2, David Li, Irfan Ibrahim
In fact, the stats only show ABC2 has the shortest tenure.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: dgc5213/ped#5

### LINKED ISSUE #129: [PE-D] Inaccurate stats when there are multiple employees have the lowest salary
It is really useful that the program shows the stats about the lowest salary and list down the relevant employees.
It works well when there is a single employee who has the lowest salary.
However, the program failed to display multiple employees who have the lowest salary.
Suggestion: display all matched employees' names or display No.of people who matched.

For testing purpose:
#1 ABC $1,000
#2 ABC2 $1,000
These two people share the same salary, and the salary is the lowest.
By right, the program shall list down both ABC, ABC2
In fact, the stats only show ABC has the lowest salary.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: dgc5213/ped#6

### LINKED ISSUE #130: [PE-D] Inaccurate stats when there are multiple employees have the longest tenure
It is really useful that the program shows the stats about the longest tenure and list down the relevant employees.
It works well when there is a single employee who has the longest tenure.
However, the program failed to display multiple employees who have the longest tenure.
Suggestion: display all matched employees' names or display No.of people who matched.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: dgc5213/ped#7

### LINKED ISSUE #131: [PE-D] Inaccurate stats when there are multiple employees have the highest salary
It is really useful that the program shows the stats about the highest salary and list down the relevant employees.
It works well when there is a single employee who has the highest salary.
However, the program failed to display multiple employees who have the highest salary.
Suggestion: display all matched employees' names or display No.of people who matched.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: dgc5213/ped#8

### PR DESCRIPTION
**Pull request by Chenduo1412**
Close #131, close #130, close #129, close #128

### CODE REVIEW

File: src/main/java/employeetracker/model/employee/UniqueEmployeeList.java [hunk 1]
```diff
@@ -163,14 +163,14 @@ public void sortEmployee(String field) {
     }
 
     /**
-     * Get the number of employees in the list.
+     * Gets the number of employees in the list.
      */
-    public int noOfemployees() {
+    public int getNoOfemployees() {
```
Comment (wz-chan) [inline src/main/java/employeetracker/model/employee/UniqueEmployeeList.java]: Perhaps it should be `getNoOfEmployees()` instead of `getNoOfemployees()` to follow Java convention?

File: src/main/java/employeetracker/model/employee/UniqueEmployeeList.java [hunk 2]
```diff
@@ -293,16 +301,16 @@ public String getShortestTenure() {
...
-    public String getAvgTenure() {
+    public String getAverageTenure() {
         Date todaysDate = new Date();
         Date dateOfJoin;
         long diffInMillies;
         long yearMiniSec = Long.parseLong("31536000000");
         long dayMiniSec = Long.parseLong("86400000");
         long totalMillies = 0;
-        long avgTensure = 0;
+        long averageTensure = 0;
```
Comment (wz-chan) [inline src/main/java/employeetracker/model/employee/UniqueEmployeeList.java]: Perhaps it should be `averageTenure ` instead of `averageTensure`? Tensure is not an english word

File: src/main/java/employeetracker/model/employee/UniqueEmployeeList.java [hunk 3]
```diff
@@ -313,9 +321,9 @@ public String getAvgTenure() {
         } catch (Exception e) {
             System.out.println(e.toString());
         }
-        avgTensure = totalMillies / internalList.size();
-        int totalYears = (int) (avgTensure / yearMiniSec);
-        int days = (int) (avgTensure / dayMiniSec - (totalYears * 365));
+        averageTensure = totalMillies / internalList.size();
```
Comment (wz-chan) [inline src/main/java/employeetracker/model/employee/UniqueEmployeeList.java]: Perhaps it should be averageTenure instead of averageTensure? Tensure is not an english word

**Review by wz-chan — CHANGES_REQUESTED** [review]
Your code looks okay. Will be good to merge if you fix some of the problems highlighted

**Review by wz-chan — APPROVED** [review]
LGTM
